name: An auto splitter needs fixes! (2)
description: Provide me with some information about what should be fixed.
title: "Issues with auto splitter for GAME_NAME"
labels: ["asl", "bug"]
assignees:
  - just-ero
body:
  - type: markdown
    attributes:
      value: |
        Please refer to the [common issues](https://github.com/just-ero/asl#issues) before creating an issue.
  - type: dropdown
    attributes:
      label: What features of the auto splitter don't work?
      multiple: true
      options:
        - start
        - split
        - reset
        - load removal/game time
  - type: checkboxes
    attributes:
      label: Describe your Issue
      options:
        - The game has recently received an update
  - type: textarea
    attributes:
      description: If there is any especially weird behavior with the timer, please describe what is happening.
  - type: textarea
    attributes:
      label: Causes and Fixes
      description: (*for experienced users only, provide known errors here*)
      placeholder: Do you know the exact cause of the problem? Broken pointers, signatures can't be resolved, level names changed? Please elaborate.
Do you already have a fix? Please pull request this repository with your proposed changes. You will be properly credited.
